# To launch locally and override base URL:
#
#   hugo server server -D -b http://localhost:1313/
#
baseurl = "https://www.pdxpythonpirates.org"
title = "Portland Python Pirates"
#author = "@i_mattman"
copyright = "Copyright © 2008–2018"
canonifyurls = true
paginate = 10
summaryLength = 40

theme = "jeffprod"

[params]
    display_urgent = true
    urgent_link = "/edx"
    urgent_link_title = "Urgent: edX Policy Change"
    urgent_date = "2018-12-13"

    course_title = "Computing in Python I: Fundamentals and Procedural Programming"
    course_url = "https://www.edx.org/course/computing-in-python-i-fundamentals-and-procedural-programming-0"
#    course_title = "Computing in Python II: Control Structures"
#    course_url = "https://www.edx.org/course/computing-in-python-ii-control-structures-0"

    meetup_url = "https://www.meetup.com/Portland-Python-Pirates/"
    slack_group = "pythonpirates"
    slack_url = "https://pythonpirates.slack.com"
    slack_join_request_url = "https://join.slack.com/t/pythonpirates/shared_invite/enQtNDYyMjg5NzEyMzM2LTlhNjAxYjJiOTVkYjA2ODE3MDc0ZTQ1YmQ2YWEwODJlZTIwY2Y5YmUzYjNhNDIxMTlhYWJjZGYwNWU5MzVkYmI"
    github_url = "https://github.com/PDXPythonPirates"

    header_image = "/img/laptop-python-books.jpg"
    include_toc = false


[taxonomies]
    tag = "tags"
    archive = "archives"

