# To launch locally and display draft documents
#
#   hugo server -D
#
# To launch behind an ngrok proxy (https://ngrok.com/)
#
#   # launch ngrok to set up proxy and generate base URL
#   ngrok http 1313
#   ...
#   # use the generated ngrok URL for the hugo base URL
#   hugo server --appendPort=false -b https://NGROK_URL
#
baseurl = "https://www.pythonpirates.org"
title = "Portland Python Pirates"
copyright = "Copyright © 2018–2019 Portland Python Pirates"
theme = "jeffprod"
googleAnalytics = "UA-131409351-1"
enableGitInfo = true
paginate = 10
summaryLength = 40

# this causes the full domain name to be prepended when using 'relURL' in templates
#canonifyurls = true


[params]
    course_title = "CS50 Web Programming with Python and JavaScript"
    course_url = "https://www.edx.org/course/cs50s-web-programming-with-python-and-javascript"

    header_image = "/img/laptop-python-books.jpg"

    # default preview information displayed in Slack and Twitter links
    preview_image = "/img/pirates-ogp-link-preview.jpg"
    preview_description = "We are a group of aspiring pythonistas helping each other improve our skills with the Python programming language through free and inexpensive online resources"

    meetup_url = "https://www.meetup.com/Portland-Python-Pirates/"
    slack_group = "pythonpirates"
    slack_url = "https://pythonpirates.slack.com"
    slack_join_request_url = "https://join.slack.com/t/pythonpirates/shared_invite/enQtNDYyMjg5NzEyMzM2LTlhNjAxYjJiOTVkYjA2ODE3MDc0ZTQ1YmQ2YWEwODJlZTIwY2Y5YmUzYjNhNDIxMTlhYWJjZGYwNWU5MzVkYmI"
    github_url = "https://github.com/PDXPythonPirates"
    twitter_url = "https://twitter.com/pythonpirates"
    include_toc = false

    # this toggles display of the urgent banner text at the top of all pages
    # individual pages can disable this with the page front matter 'display_urgent: false'
    #display_urgent = true

    # this overrides the header image for all pages;  comment out to disable
    #urgent_header_image = "/img/urgent-edx.jpg"

    urgent_url = "/edx"
    # text displayed in top page nav; unset this to remove
    urgent_nav_title = "edX Policy Change"
    # link text displayed in banner box at the top of content section
    urgent_link_title = "Urgent: edX Policy Change"
    urgent_date = "2018-12-13"

[taxonomies]
    tag = "tags"
    archive = "archives"

