# To launch locally and display draft documents
#
#   hugo server -D
#
# To launch behind an ngrok proxy (https://ngrok.com/)
#
#   # launch ngrok to set up proxy and generate base URL
#   ngrok http 1313
#   ...
#   # use the generated ngrok URL for the hugo base URL
#   hugo server --appendPort=false -b https://NGROK_URL
#
baseurl = "https://www.pythonpirates.org"
title = "Portland Python Pirates"
copyright = "Copyright © 2018–2020 Portland Python Pirates"
theme = "jeffprod"
googleAnalytics = "UA-131409351-1"
enableGitInfo = true
enableEmoji = true
paginate = 10
summaryLength = 40

# this causes the full domain name to be prepended when using 'relURL' in templates
#canonifyurls = true


[params]
    course_title = "Learning Python (course 3)"
    course_url = "https://www.lynda.com/learning-paths/Developer/become-a-python-developer"

    header_image = "/img/laptop-python-books.jpg"

    # default preview information displayed in Slack and Twitter links
    images = ["/img/ogp-preview-laptop-500.jpg"]
    description = "We are a group of aspiring pythonistas helping each other improve our skills with the Python programming language through free and inexpensive online resources"

    meetup_url = "https://www.meetup.com/Portland-Python-Pirates/"
    slack_group = "pythonpirates"
    slack_url = "https://pythonpirates.slack.com"
    slack_join_request_url = "https://join.slack.com/t/pythonpirates/shared_invite/enQtNDYyMjg5NzEyMzM2LThiZTFkNWQ0YTliZjYzNTA5MGVjOWZiNTQzN2QxMGZlMjBjMDJiOWI3YmJlMTBlMjBiM2VhYjA4NjEyODMzZjk"
    github_url = "https://github.com/PDXPythonPirates"
    github_version_url = "https://github.com/PDXPythonPirates/pythonpirates.org/commit/"
    twitter_url = "https://twitter.com/pythonpirates"
    include_toc = false

    # this toggles display of the urgent banner text at the top of all pages
    # individual pages can disable this with the page front matter 'display_urgent: false'
    #display_urgent = true

    # this overrides the header image for all pages;  comment out to disable
    #urgent_header_image = "/img/urgent-edx.jpg"

    urgent_url = "/edx"
    # text displayed in top page nav; unset this to remove
    urgent_nav_title = "edX Policy Change"
    # link text displayed in banner box at the top of content section
    urgent_link_title = "Urgent: edX Policy Change"
    urgent_date = "2018-12-13"

[frontmatter]
    # default order checks Git first
    #lastmod = [":git", "lastmod", "date", "publishDate"]
    lastmod = ["lastmod", ":git", "date", "publishDate"]


[taxonomies]
    tag = "tags"
    archive = "archives"

